# Generated by Django 4.1.5 on 2023-01-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_bedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bedroom',
            field=models.ManyToManyField(to='listing.bedroom'),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ManyToManyField(to='listing.city'),
        ),
    ]
