# Generated by Django 4.1.5 on 2023-01-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_post_bedroom_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
