# Generated by Django 4.1.5 on 2023-01-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='bedroom',
            field=models.ManyToManyField(related_name='posts', to='listing.bedroom'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.ManyToManyField(related_name='posts', to='listing.city'),
        ),
    ]
