# Generated by Django 4.1.5 on 2023-01-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_post_slug_alter_post_bedroom_alter_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
