# Generated by Django 4.1.5 on 2023-01-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bedroom',
        ),
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.DeleteModel(
            name='Bedroom',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='post',
            name='bedroom',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
